project_name: check-ircd
build:
  binary: check-ircd
  goos:
    - linux
    - freebsd
  goarch:
    - amd64
fpm:
  homepage: https://github.com/lrstanley/nagios-check-ircd
  maintainer: Liam Stanley <me@liamstanley.io>
  description: Nagios utility for monitoring the health of an ircd.
  license: MIT
  formats:
    - deb
    - rpm
snapshot:
  name_template: snapshot-{{.Commit}}
release:
  draft: true
